"""Fix user relationships and backrefs

Revision ID: 1292c668dcd0
Revises: 61338c4ff295
Create Date: 2026-02-22 17:39:03.214897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1292c668dcd0'
down_revision: Union[str, Sequence[str], None] = '61338c4ff295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('match_time', sa.String(length=50), nullable=True))
    op.add_column('matches', sa.Column('round_number', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('teams_ibfk_1'), 'teams', type_='foreignkey')
    op.drop_column('teams', 'tournament_id')
    op.add_column('tournaments', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'is_active')
    op.add_column('teams', sa.Column('tournament_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('teams_ibfk_1'), 'teams', 'tournaments', ['tournament_id'], ['id'])
    op.drop_column('matches', 'round_number')
    op.drop_column('matches', 'match_time')
    # ### end Alembic commands ###
