"""group name

Revision ID: 2ea586a08103
Revises: b8fe7d1a3ed6
Create Date: 2026-03-01 20:32:34.011910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea586a08103'
down_revision: Union[str, Sequence[str], None] = 'b8fe7d1a3ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('group_name', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'group_name')
    # ### end Alembic commands ###
