"""add photo and referee_report

Revision ID: 335b667b4097
Revises: 9dc6aa2c3805
Create Date: 2026-03-04 20:06:11.895683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335b667b4097'
down_revision: Union[str, Sequence[str], None] = '9dc6aa2c3805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('photo', sa.String(length=500), nullable=True))
    op.add_column('matches', sa.Column('referee_report', sa.String(length=500), nullable=True))
    op.add_column('referees', sa.Column('photo', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referees', 'photo')
    op.drop_column('matches', 'referee_report')
    op.drop_column('coaches', 'photo')
    # ### end Alembic commands ###
