"""Add email column to Referee table

Revision ID: 487763b37813
Revises: 1292c668dcd0
Create Date: 2026-02-23 21:31:20.434180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487763b37813'
down_revision: Union[str, Sequence[str], None] = '1292c668dcd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('trophy_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'trophy_image')
    # ### end Alembic commands ###
