"""Add email column to Referee table

Revision ID: 61338c4ff295
Revises: 746f38ec1cac
Create Date: 2026-02-22 15:19:36.676624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61338c4ff295'
down_revision: Union[str, Sequence[str], None] = '746f38ec1cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referees', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'referees', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referees', type_='unique')
    op.drop_column('referees', 'email')
    # ### end Alembic commands ###
