"""Add jersey_number and photo to Player

Revision ID: 794776e79f7f
Revises: 487763b37813
Create Date: 2026-02-27 02:18:09.416963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '794776e79f7f'
down_revision: Union[str, Sequence[str], None] = '487763b37813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('photo', sa.String(length=500), nullable=True))
    op.add_column('players', sa.Column('jersey_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'jersey_number')
    op.drop_column('players', 'photo')
    # ### end Alembic commands ###
