"""add penalty fields

Revision ID: 9dc6aa2c3805
Revises: da512d2cc94f
Create Date: 2026-03-04 09:50:36.202830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc6aa2c3805'
down_revision: Union[str, Sequence[str], None] = 'da512d2cc94f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('penalty_home', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('penalty_away', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'penalty_away')
    op.drop_column('matches', 'penalty_home')
    # ### end Alembic commands ###
