"""Add lineups and events

Revision ID: b8fe7d1a3ed6
Revises: fbfb89d0ed77
Create Date: 2026-02-27 21:41:18.416437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8fe7d1a3ed6'
down_revision: Union[str, Sequence[str], None] = 'fbfb89d0ed77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
