"""..

Revision ID: da512d2cc94f
Revises: f829f62f44fd
Create Date: 2026-03-03 22:16:03.428627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'da512d2cc94f'
down_revision: Union[str, Sequence[str], None] = 'f829f62f44fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'penalty_away')
    op.drop_column('matches', 'penalty_home')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('penalty_home', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('penalty_away', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
