"""add penalty fields

Revision ID: f829f62f44fd
Revises: 2ea586a08103
Create Date: 2026-03-03 22:12:45.601038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f829f62f44fd'
down_revision: Union[str, Sequence[str], None] = '2ea586a08103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('penalty_home', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('penalty_away', sa.Integer(), nullable=True))
    op.alter_column('matches', 'round_number',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'round_number',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.drop_column('matches', 'penalty_away')
    op.drop_column('matches', 'penalty_home')
    # ### end Alembic commands ###
